### ISSUE TITLE
при переключении вкладок в браузере теряется соединение

### ISSUE THREAD

**Issue by north69** [storageddd/scrump.io#2]
проблема: при уходе с вкладки с приложением и возвратом обратно теряется соединение с сервером и информация на странице не обновляется.

что сделать: переподключаться если теряется соединение

<img width="1502" alt="image" src="https://github.com/user-attachments/assets/1c8986f5-537d-4e6d-8aeb-1a2d1a313f85">

**Comment by storageddd** [comment]
нужно больше инфы между какими вкладками конкретно и желательно скрин, чтобы было проще воспроизводить

**Comment by north69** [comment]
добавил скрин, обновил описание

**Comment by storageddd** [comment]
1. Добавлен реконнект при потере соединения
2. Добавлена фича открытия комнаты в нескольких вкладках
